/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autoescolabmi;

import db.UsuarioDAO;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Usuario;

/**
 *
 * @author Gideon
 */
public class Login extends javax.swing.JDialog {

    private Usuario usuarioAutenticado;
    private boolean usuarioLogado;
    
    private void fazerLogin() throws Exception{
        Usuario usuario = new Usuario();
        usuario.setLogin(txtUsuario.getText());
        usuario.setSenha(txtSenha.getText());       
        
        //Verifica o usuário e a senha
        this.autenticar(usuario);
        this.verificaPermissoesUsuario();    
        
        usuarioLogado = true;
        dispose(); 
    }   
    
    public boolean estaLogado(){
        return this.usuarioLogado;
    }
    
    private void autenticar(Usuario usuario) throws Exception{
        
        Usuario usuarioBanco = new UsuarioDAO().procurarLogin(usuario.getLogin());
        
        if(usuarioBanco == null){
            throw new Exception("Usuario não encontrado");
            
        } else if(!usuarioBanco.getSenha().equals(usuario.getSenha())){
            throw new Exception("Senha digitada incorretamente");
            
        }
        
        this.usuarioAutenticado = usuarioBanco;                   
    }
    
    private void verificaPermissoesUsuario() throws Exception{
        if(this.usuarioAutenticado == null){
            throw new Exception ("Ocorreu um erro na autenticação do usuário");
        }
        
        Date hoje = new Date();
        SimpleDateFormat df = new SimpleDateFormat("dd/mm/yyyy");
        if(this.usuarioAutenticado.getDataInicio() != null){
            if(this.usuarioAutenticado.getDataInicio().getTime() < hoje.getTime()){
                String exc = "Usuário não tem permissão para acessar o sistema nesta data.\n" +
                             "Data início da vigência: " + df.format(this.usuarioAutenticado.getDataInicio());
            
                throw new Exception (exc);
            }
        }
        
        if(this.usuarioAutenticado.getDataFim() != null){
            if(this.usuarioAutenticado.getDataFim().getTime() > hoje.getTime()){
                String exc = "Usuário não tem permissão para acessar o sistema nesta data.\n" +
                             "Data fim da vigência: " + df.format(this.usuarioAutenticado.getDataFim());
            
                throw new Exception (exc);
            }
        }
        /*
        df = new SimpleDateFormat("HH:mm");
        Calendar agora = Calendar.getInstance();
        if(this.usuarioAutenticado.getHorarioFim()!= null){
            if(this.usuarioAutenticado.getHorarioFim().getTime() > (agora.get(Calendar.MINUTE) * 60000 + agora.get(Calendar.HOUR_OF_DAY) * 60000 * 60)){
                String exc = "Usuário não tem permissão para acessar o sistema neste horário.\n" +
                             "Horário fim da vigência: " + df.format(this.usuarioAutenticado.getHorarioFim());
            
                throw new Exception (exc);
            }
        }
        
        if(this.usuarioAutenticado.getHorarioInicio() != null){
            if(this.usuarioAutenticado.getHorarioInicio().getTime() <(agora.get(Calendar.MINUTE) * 60000 + agora.get(Calendar.HOUR_OF_DAY) * 60000 * 60)){
                String exc = "Usuário não tem permissão para acessar o sistema neste horário.\n" +
                             "Horário início da vigência: " + df.format(this.usuarioAutenticado.getHorarioInicio());
            
                throw new Exception (exc);
            }
        }*/
    }
    
    /**
     * Creates new form Login
     */
    public Login(java.awt.Frame parent) {
        super(parent, true);        
        super.setSize(336,400);
        super.setResizable(false);
        super.setLocationRelativeTo(parent);
        
        this.usuarioLogado = false;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Login do Sistema");

        jLabel3.setText("Usuário:");

        jLabel4.setText("Senha:");

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        txtUsuario.setText("ADMIN");
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        txtSenha.setText("ADMIN");
        txtSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel2)))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEntrar)
                .addGap(131, 131, 131))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnEntrar)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        try{
            this.fazerLogin();
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
